#!/usr/bin/env bash
set -e
if [ -f "$HOME/.acme-backup/.env" ]; then
  set -a
  . $HOME/.acme-backup/.env
  set +a
fi

CUR_DIR="$PWD"
TMP_DIR=`mktemp -d`
cd $TMP_DIR
FOLDER_NAME=`date +"%Y_%m_%d__%H_%M_%S"`
KEY_FILE="key.bin"
openssl rand -hex -out $KEY_FILE 64
DUMP_FILE="dump.tar.gz"

KEY_ENC_FILE="$KEY_FILE.enc"
DUMP_ENC_FILE="$DUMP_FILE.enc"

tar -zcvf $DUMP_FILE --directory=$HOME .acme.sh
openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -in $DUMP_FILE -out $DUMP_ENC_FILE -pass file:$KEY_FILE
rm $DUMP_FILE
openssl rsautl -encrypt -pubin -inkey $HOME/.acme-backup/key.pub -in $KEY_FILE -out $KEY_ENC_FILE
rm $KEY_FILE

find "$TMP_DIR" -mindepth 1 -maxdepth 1 -type f -printf "%f\0" | AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION" AWS_DEFAULT_OUTPUT="$AWS_DEFAULT_OUTPUT" xargs -0 -I {} $HOME/.local/bin/aws s3 cp --no-progress "{}" "s3://$AWS_S3_BUCKET_NAME/$FOLDER_NAME/{}"
cd $CUR_DIR
rm -rf $TMP_DIR